### ISSUE TITLE
Inner otheragent2 resets to initialization

### ISSUE THREAD

**Issue by cooijmanstim** [Silent-Zebra/POLA#6]
There is a bug in `inner_step_get_grad_otheragent2` where the return value uses `trainstate_th2.params` and `trainstate_val2.params`. I think that should be `trainstate_th2_.params` and `trainstate_val2_.params`? As it is, it takes params from the trainstates in the global scope which haven't been trained. However, with the way the result of `inner_step_get_grad_otheragent2` is used in the caller, I think this bug should have no effect unless `args.inner_steps > 2`.

https://github.com/Silent-Zebra/POLA/blob/6b07e89317b07d91216db9d02c1f915f9313b66a/jax_files/POLA_dice_jax.py#L541

**Comment by Silent-Zebra** [comment]
Thanks for pointing this out! I think you're right in your comment and the effect. I'll fix this and the other issue you pointed out.

**Comment by Silent-Zebra** [comment]
Closing as fixes have been implemented and experiments rerun (see updated readme)
